### ISSUE TITLE
Add Usage in functional Vue Component.

### ISSUE THREAD

**Issue by realdennis** [yyx990803/vue-hooks#15]
According to https://github.com/yyx990803/vue-hooks/issues/14 , I thought we can add some use case of **vue-hooks in function component** (maybe jsx).

Below is a very simple demo, could I send a PR to add this?

```jsx
import { withHooks, useState } from 'vue-hooks';

const Counter = () => {
  const [count, setCount] = useState(0);
  return (
    <div>
      <p>
        Current value is <strong>{count}</strong>
      </p>
      <button onClick={() => setCount(count + 1)}>+</button>
      <button onClick={() => setCount(count - 1)}>-</button>
    </div>
  );
};
export default withHooks(h => h(Counter));
```

**Comment by yyx990803** [comment]
This seems to be exactly the same with the example in the README in terms of being "functional"...

**Comment by realdennis** [comment]
Feel sorry, just want make the docs explicit for programmers who are used to use jsx.

I'll close this issue later.
Hope I didn't bother you!
